<script setup lang="ts">

</script>

<template>
<div class="MainBody">
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam neque. Nam quis nulla. Praesent vitae arcu tempor neque lacinia pretium. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Mauris metus. Morbi scelerisque luctus velit. Sed convallis magna eu sem. Integer malesuada.</p>

  <p>Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Fusce consectetuer risus a nunc. Aliquam ante. Aliquam in lorem sit amet leo accumsan lacinia. Curabitur sagittis hendrerit ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In rutrum.</p>

  <p>Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Vivamus luctus egestas leo. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Nulla est. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Curabitur bibendum justo non orci. Proin in tellus sit amet nibh dignissim sagittis. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Maecenas libero.</p>

  <p>Phasellus faucibus molestie nisl. Et harum quidem rerum facilis est et expedita distinctio. Cras elementum. Praesent in mauris eu tortor porttitor accumsan. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Etiam dictum tincidunt diam. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.</p>

  <p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Aliquam erat volutpat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Praesent in mauris eu tortor porttitor accumsan. Nullam at arcu a est sollicitudin euismod. Etiam dictum tincidunt diam. Integer in sapien. Aliquam erat volutpat. Nunc dapibus tortor vel mi dapibus sollicitudin. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Nam quis nulla. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo.</p>

  <p>Donec iaculis gravida nulla. Nulla non arcu lacinia neque faucibus fringilla. Fusce tellus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Fusce aliquam vestibulum ipsum. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Integer lacinia. Aenean id metus id velit ullamcorper pulvinar. Nam quis nulla.</p>

  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam neque. Nam quis nulla. Praesent vitae arcu tempor neque lacinia pretium. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Mauris metus. Morbi scelerisque luctus velit. Sed convallis magna eu sem. Integer malesuada.</p>

  <p>Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Fusce consectetuer risus a nunc. Aliquam ante. Aliquam in lorem sit amet leo accumsan lacinia. Curabitur sagittis hendrerit ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In rutrum.</p>

  <p>Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Vivamus luctus egestas leo. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Nulla est. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Curabitur bibendum justo non orci. Proin in tellus sit amet nibh dignissim sagittis. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Maecenas libero.</p>

  <p>Phasellus faucibus molestie nisl. Et harum quidem rerum facilis est et expedita distinctio. Cras elementum. Praesent in mauris eu tortor porttitor accumsan. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Etiam dictum tincidunt diam. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.</p>

  <p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Aliquam erat volutpat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Praesent in mauris eu tortor porttitor accumsan. Nullam at arcu a est sollicitudin euismod. Etiam dictum tincidunt diam. Integer in sapien. Aliquam erat volutpat. Nunc dapibus tortor vel mi dapibus sollicitudin. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Nam quis nulla. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo.</p>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam neque. Nam quis nulla. Praesent vitae arcu tempor neque lacinia pretium. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Mauris metus. Morbi scelerisque luctus velit. Sed convallis magna eu sem. Integer malesuada.</p>

  <p>Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Fusce consectetuer risus a nunc. Aliquam ante. Aliquam in lorem sit amet leo accumsan lacinia. Curabitur sagittis hendrerit ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In rutrum.</p>

  <p>Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Vivamus luctus egestas leo. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Nulla est. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Curabitur bibendum justo non orci. Proin in tellus sit amet nibh dignissim sagittis. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Maecenas libero.</p>

  <p>Phasellus faucibus molestie nisl. Et harum quidem rerum facilis est et expedita distinctio. Cras elementum. Praesent in mauris eu tortor porttitor accumsan. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Etiam dictum tincidunt diam. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.</p>

  <p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Aliquam erat volutpat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Praesent in mauris eu tortor porttitor accumsan. Nullam at arcu a est sollicitudin euismod. Etiam dictum tincidunt diam. Integer in sapien. Aliquam erat volutpat. Nunc dapibus tortor vel mi dapibus sollicitudin. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Nam quis nulla. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo.</p>


  <p>Vivamus ac leo pretium faucibus. Fusce consectetuer risus a nunc. Aliquam ante. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Nullam eget nisl. Nunc dapibus tortor vel mi dapibus sollicitudin. Mauris tincidunt sem sed arcu. Curabitur bibendum justo non orci. Maecenas aliquet accumsan leo. Et harum quidem rerum facilis est et expedita distinctio. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Phasellus rhoncus. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? In convallis.</p></div>
</template>

<style scoped>
.MainBody {
  display: flex;
  flex-direction: column;
  width: 80%;
  border-radius:30px;
  background-color: greenyellow;
  margin: 0 auto;
  text-wrap: wrap;
}
</style>